// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-QqXlVwyrs_o6SuDwxunSn7stbZ1nrk',
    appId: '1:662248853793:web:c05a743ba9630a85142e60',
    messagingSenderId: '662248853793',
    projectId: 'login-app-3fcdc',
    authDomain: 'login-app-3fcdc.firebaseapp.com',
    storageBucket: 'login-app-3fcdc.appspot.com',
    measurementId: 'G-7KKLZPF3TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqu3DgFfUX13PP6YIIommVGXdx3p2rk4Q',
    appId: '1:662248853793:android:1e1ea82f4446cee3142e60',
    messagingSenderId: '662248853793',
    projectId: 'login-app-3fcdc',
    storageBucket: 'login-app-3fcdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyn08bZ005dOx4N8rNryFRti5hrz6K3Vg',
    appId: '1:662248853793:ios:c4f9ca1309de0ac6142e60',
    messagingSenderId: '662248853793',
    projectId: 'login-app-3fcdc',
    storageBucket: 'login-app-3fcdc.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyn08bZ005dOx4N8rNryFRti5hrz6K3Vg',
    appId: '1:662248853793:ios:77e50ea735caf215142e60',
    messagingSenderId: '662248853793',
    projectId: 'login-app-3fcdc',
    storageBucket: 'login-app-3fcdc.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
